-- Add new columns to coupons table
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS min_order NUMERIC DEFAULT 0;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS one_time_use BOOLEAN DEFAULT FALSE;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS used_count INTEGER DEFAULT 0;
